#!/bin/sh
set -e -u -C

for t in "$@"
do
    printf '%s ... ' "$t"
    ln -s generic-test "${t}.t"
    echo eggs > "${t}.in"
    echo ham > "${t}.exp"
    printf 'ok\n'
done

# vim:ts=4 sts=4 sw=4 et
